// File generated by FlutterFire CLI (placeholder).
//
// TODO: Zastąp tę zawartość prawdziwym configiem dla web. Dwa sposoby:
//
//  1) (zalecane) W harcapp_web/:
//       dart pub global activate flutterfire_cli
//       flutterfire configure --project=harcapp --platforms=web
//     Wybierz aplikację web w projekcie `harcapp` (lub utwórz nową).
//     Polecenie nadpisze ten plik prawdziwymi kluczami.
//
//  2) Ręcznie: Firebase Console → projekt `harcapp` → Project settings →
//     General → Your apps → Add app → Web. Skopiuj wartości z `firebaseConfig`
//     do `web` poniżej (apiKey, authDomain, projectId, storageBucket,
//     messagingSenderId, appId, measurementId).
//
// Do czasu uzupełnienia kIsWeb → UnsupportedError; main.dart łapie wyjątek
// i kontynuuje bez Firebase (zob. lib/_common_classes/firebase.dart).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure --project=harcapp --platforms=web` in harcapp_web/.',
      );
    }
    throw UnsupportedError(
      'harcapp_web targets web only; no Firebase config for ${defaultTargetPlatform.name}.',
    );
  }
}
