// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'harcapp_web targets web only; no Firebase config for ${defaultTargetPlatform.name}.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVCOLJOdI0z-qh8g1VmzMBk0jvYJ9xtSs',
    appId: '1:601196144720:web:14a2c3e1aa777fc1eac955',
    messagingSenderId: '601196144720',
    projectId: 'harcapp',
    authDomain: 'harcapp.firebaseapp.com',
    databaseURL: 'https://harcapp.firebaseio.com',
    storageBucket: 'harcapp.firebasestorage.app',
    measurementId: 'G-T3VQDKT50M',
  );
}
